// картинка 1920х890
export const projects = [
    {
        id: "portfolio",
        name: "Portfolio",
        preview: "/images/portfolio.png",
        stack: "JS, Svelte",
        link: "https://sialiss.github.io/portfolio/",
        about: "My portfolio. I chose Svelte because I was interested in doing something with it, it feels good. The list of projects is automatically filled with elements from the JS object, similarly, the page for a separate project is filled in just by reading the URL. You can view my work here without opening it in a new tab.",
        github: "https://github.com/sialiss/portfolio",
    },
    {
        id: "cards",
        name: "Cards",
        preview: "/images/cards.png",
        stack: "JS, React",
        link: "https://sialiss.github.io/cards/",
        about: "Trello-like app made with React. There is a drag-and-click and a form for creating cards. This was the first time I've done something in React, so it's quite simple.",
        github: "https://github.com/sialiss/cards",
    },
    {
        id: "json_table",
        name: "JSON Table",
        preview: "/images/table.png",
        stack: "JS",
        link: "https://sialiss.github.io/test-infotecs/",
        about: "Test task for the internship. I didn't pass, but it was a good experience anyway. The script parses JSON and processes it, creating a table. Objects (rows) can be changed, you can hide columns in the table and sort it.",
        github: "https://github.com/sialiss/test-infotecs",
    },
    {
        id: "kotoglad",
        name: "Kotoglad",
        preview: "/images/cats.png",
        stack: "JS",
        link: "https://sialiss.github.io/Clicker/",
        about: "It's my first attemp at JS. It was necessary to make a clicker, so here it is. The balance is not well thought out, the images are not mine. But it's done and it works.",
        github: "https://github.com/sialiss/Clicker",
    },
    // {
    //     id: "",
    //     name: "",
    //     preview: "/images/name.png",
    //     stack: "",
    //     link: "",
    //     about: "text",
    //     github: "",
    // },
]