export const projects = [
    {
        id: "portfolio",
        name: "Portfolio",
        preview: "/images/portfolio.png",
        stack: "JS, Svelte",
        iframe_link: "https://sialiss.github.io/portfolio/",
        about: "text",
        github: "https://github.com/sialiss/portfolio",
    },
    {
        id: "cards",
        name: "Cards",
        preview: "/images/cards.png",
        stack: "JS, React",
        iframe_link: "https://sialiss.github.io/cards/",
        about: "text",
        github: "https://github.com/sialiss/cards",
    },
    {
        id: "json_table",
        name: "JSON Table",
        preview: "/images/table.png",
        stack: "JS",
        iframe_link: "https://sialiss.github.io/test-infotecs/",
        about: "text",
        github: "https://github.com/sialiss/test-infotecs",
    },
    {
        id: "kotoglad",
        name: "Kotoglad",
        preview: "/images/cats.png",
        link: "/project",
        stack: "JS",
        iframe_link: "https://sialiss.github.io/Clicker/",
        about: "text",
        github: "https://github.com/sialiss/Clicker",
    },
    // {
    //     id: "",
    //     name: "",
    //     preview: "/images/name.png",
    //     stack: "",
    //     iframe_link: "",
    //     about: "text",
    //     github: "",
    // },
]