export const projects = [
    {
        id: "flowerize",
        width: "1024",
        height: "600",
        name: "Flowerize",
        preview: "/images/flowerize.png",
        stack: "Godot",
        embed_link: "https://itch.io/embed-upload/6450745?color=ACC6D0",
        link: "https://saphielle.itch.io/flowerize",
        about: "Made by me and my friend for Kenney GameJam 2022. Theme: growth, 2 day limit. I created gamedesign (idea, mechanics, level design) and art (stylistics, animations, coloring, music). The assets are made by Kenney (it's the jam condition), but the player character is created from a combination of two assets, and I drew the animations frame by frame.",
        github: "https://github.com/sialiss/GMTK-gamejam2022",
    },
    {
        id: "dice",
        width: "1024",
        height: "600",
        name: "Oh no! The dice came to life!",
        preview: "/images/dice2.png",
        stack: "Godot",
        embed_link: "https://itch.io/embed-upload/6179916?color=333333",
        link: "https://saphielle.itch.io/oh-no-the-dice-came-to-life",
        about: "We (me and two of my friends) participated in GMTK GameJam 2022, where we had to make a game on a given topic in 48 hours. This year the theme was 'Roll the dice', so we made a game where you play as a dice that is attacked by players' pieces (hats and pawns). Depending on the number on the top edge, different abilities are used, and HP is displayed as the progress of passing the chip to the end (this is from the bottom).",
        github: "https://github.com/sialiss/GMTK-gamejam2022",
    },
]
